server:
  port: 8889

spring:

  main:
    allow-circular-references: true

  jackson:
    time-zone: GMT+8

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 100MB

  redis:
    host: 
    port: 6379
    password:

  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql:///music?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
      username: 
      password: 

token:
  expireTime: 259200000
  secretKey: abcdefghijklmnopqrstuvwxyz

upload:
  mode: local

  local:
    # nginx映射本地文件路径
    url: 
    # 本地文件存储路径
    path: /usr/local/upload/

mybatis-plus:
  global-config:
    db-config:
      id-type: assign_id
